# Generated by Django 5.1.4 on 2024-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reset_password_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
