# Generated by Django 5.1.4 on 2024-12-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_reset_password_code_expiration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
    ]
