# Generated by Django 5.1.4 on 2024-12-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['created_at'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
